apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: 423311849040.dkr.ecr.ap-southeast-2.amazonaws.com/dev/hello-world:ddda070d5ed5cbf0a764b17751f62b9037c2877d
